apiVersion: v1
kind: Service
metadata:
  name: proxy-deployment
  labels:
    app: proxy-deployment
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: proxy-deployment-tls
spec:
  selector:
    app: proxy-deployment
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: proxy
      port: 4180
      protocol: TCP
      targetPort: 4180
  sessionAffinity: None
  type: ClusterIP
